### ISSUE TITLE
missing scope error

### ISSUE THREAD

**Issue by ajRiverav** [alexwlchan/backup-slack#4]
There may be a problem with the API

```
Traceback (most recent call last):
 [...]
  File "/usr/local/lib/python2.7/site-packages/slacker/__init__.py", line 191, in list
    return self.get('users.list', params={'presence': int(presence)})
  File "/usr/local/lib/python2.7/site-packages/slacker/__init__.py", line 117, in get
    api, **kwargs
  File "/usr/local/lib/python2.7/site-packages/slacker/__init__.py", line 99, in _request
    raise Error(response.error)
slacker.Error: missing_scope
```

**Comment by PhiBabin** [comment]
This happens when the token does not have the [required scope](https://api.slack.com/docs/oauth-scopes). Basically give permission to `:read` and `:history` for **everything** (groups, im, channels, team, etc.). Keep doing it until the missing scope go away.
The script should check, its scope before using the api.

**Comment by fixbugsnow** [comment]
instead of being so generic in providing auth accesses (weaker/loose security), we can be very specific in auth access needs and provide ONLY the accesses that are needed for the backups (this is much safer)

so all we need to provide are these accesses (easily done thru Slack API's OAuth's **Scopes** part of the page manually or making use of OAuth API calls to automate these access requests - to self-grant auths when the user already have higher level accesses) :

channels:history
channels:read
groups:history
groups:read
im:history
im:read

incidentally, the "missing_scope" error msg's super short text's problem has it's roots in "__ init __.BaseAPI()", wherein currently on an error, only the error text is shown:

e.g. "slacker.Error: missing_scope"

which hides the detailed reasons for the error, 'coz of usage of just "error.text", instead of using "error.raw", in line # 112

this change has been implemented in these lines in my below forked repo:
https://github.com/fixbugsnow/slacker/blob/master/slacker/__init__.py#L102-L112

making this change will show the full error details, so the users knows all the reasons behind the error, just like Slack's API "Tester" shows the detailed results for errors:

e.g. slacker.Error: '{"ok": false,"error": "missing_scope","needed": "users:read","provided": "admin,identify"}

pgm flow happens (and still will happen) like so:

```
Traceback (most recent call last):
* * *
  File "c:\program files (x86)\python37\lib\site-packages\slacker\__init__.py", line 332, in list
    return self.get('users.list', params={'presence': int(presence)})
  File "c:\program files (x86)\python37\lib\site-packages\slacker\__init__.py", line 121, in get
    api, **kwargs
  File "c:\program files (x86)\python37\lib\site-packages\slacker\__init__.py", line 103, in _request
    raise Error(response.raw)
slacker.Error: {"ok":false,"error":"missing_scope","needed":"users:read","provided":"admin,identify"}
```

have requested for this change to be implemented in the original repo (https://github.com/os/slacker), for benefit of users of that repo and it's forks
